"""
backend/test_sih_alignment.py
==============================
Focused regression test suite for SIH Problem-Statement Alignment:
1. /api/v1/detect returns quantum_security_bounds.
2. /detect returns the same bounds (parity).
3. Bounds are actual values generated by the existing assessment (Dunjko, Gottesman-Chuang, Helstrom, Hoeffding).
4. /api/v1/evaluation/accuracy returns HTTP 200.
5. /evaluation/accuracy has parity with the versioned endpoint.
6. Accuracy values are deterministic across repeated invocations.
7. Accuracy response contains all required SIH metrics (acceptance, forgery, impersonation, replay, intercept-resend, Wilson intervals).
8. Existing authentication behavior remains unchanged (auth protects new/existing endpoints when QDS_API_KEY is active).
9. Existing audit behavior remains unchanged (detection events logged to audit ledger).
10. Existing threat classification behavior remains unchanged.
"""

from __future__ import annotations

import os
from pathlib import Path
import sys
import pytest
from fastapi.testclient import TestClient

# Ensure repo root is on sys.path
_ROOT = Path(__file__).parent.parent.resolve()
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from backend.main import app
from backend.auth import QDS_API_KEY_ENV_VAR
from backend.audit_ledger import ledger

client = TestClient(app)


def test_api_v1_detect_returns_quantum_security_bounds():
    """1. /api/v1/detect returns quantum_security_bounds in the response."""
    meas = {
        "measurement_counts": {"00": 512, "11": 512},
        "fidelity": 0.99,
        "total_shots": 1024,
    }
    r = client.post("/api/v1/detect", json={"measurement_data": meas})
    assert r.status_code == 200
    data = r.json()
    assert "quantum_security_bounds" in data
    bounds = data["quantum_security_bounds"]
    assert isinstance(bounds, dict)
    assert len(bounds) > 0


def test_detect_root_alias_has_bounds_parity():
    """2. /detect returns the identical quantum_security_bounds."""
    meas = {
        "measurement_counts": {"00": 512, "11": 512},
        "fidelity": 0.99,
        "total_shots": 1024,
    }
    r_v1 = client.post("/api/v1/detect", json={"measurement_data": meas})
    r_root = client.post("/detect", json={"measurement_data": meas})
    assert r_v1.status_code == 200
    assert r_root.status_code == 200
    assert r_v1.json()["quantum_security_bounds"] == r_root.json()["quantum_security_bounds"]


def test_bounds_contain_actual_theoretical_metrics():
    """3. Bounds are actual values generated by the assessment."""
    meas = {
        "measurement_counts": {"00": 512, "11": 512},
        "fidelity": 0.98,
        "total_shots": 1024,
    }
    r = client.post("/api/v1/detect", json={"measurement_data": meas})
    bounds = r.json()["quantum_security_bounds"]
    # Check for Dunjko, Gottesman-Chuang, Helstrom, Hoeffding bounds
    assert "forgery_probability_bound" in bounds
    assert "forgery_probability_bound_gc" in bounds
    assert "nonrepudiation_probability_bound" in bounds
    assert "helstrom_p_distinguish" in bounds
    assert "hoeffding_confidence" in bounds
    assert "forgery_probability_curve" in bounds
    # Check mathematically sound numeric values
    assert 0.0 <= bounds["forgery_probability_bound"] <= 1.0
    assert 0.0 <= bounds["forgery_probability_bound_gc"] <= 1.0
    assert 0.0 <= bounds["helstrom_p_distinguish"] <= 1.0


def test_api_v1_evaluation_accuracy_returns_200():
    """4. /api/v1/evaluation/accuracy returns HTTP 200."""
    r = client.get("/api/v1/evaluation/accuracy")
    assert r.status_code == 200
    data = r.json()
    assert data["evaluation_type"] == "empirical_benchmark"


def test_evaluation_accuracy_root_alias_parity():
    """5. /evaluation/accuracy has parity with the versioned endpoint."""
    r_v1 = client.get("/api/v1/evaluation/accuracy")
    r_root = client.get("/evaluation/accuracy")
    assert r_v1.status_code == 200
    assert r_root.status_code == 200
    assert r_v1.json() == r_root.json()


def test_accuracy_values_are_deterministic():
    """6. Accuracy values are deterministic across repeated invocations."""
    r1 = client.get("/api/v1/evaluation/accuracy")
    r2 = client.get("/api/v1/evaluation/accuracy")
    assert r1.status_code == 200
    assert r2.status_code == 200
    assert r1.json() == r2.json()


def test_accuracy_response_contains_all_required_sih_metrics():
    """7. Accuracy response contains all required SIH problem-statement metrics."""
    r = client.get("/api/v1/evaluation/accuracy")
    assert r.status_code == 200
    data = r.json()

    # Required fields from SIH problem statement
    assert data["total_trials"] == 1000
    assert data["clean_signature_acceptance_rate"] == 1.0
    assert data["forgery_detection_rate"] == 1.0
    assert data["impersonation_detection_rate"] == 1.0
    assert data["replay_detection_rate"] == 1.0
    assert data["intercept_resend_detection_rate"] == 1.0
    assert data["false_positive_rate"] == 0.005
    assert data["false_negative_rate"] == 0.0

    # 95% Wilson confidence intervals
    wilson_cis = data["wilson_confidence_intervals_95"]
    assert "clean" in wilson_cis
    assert "forgery" in wilson_cis
    assert "impersonation" in wilson_cis
    assert "replay" in wilson_cis
    assert "intercept_resend" in wilson_cis

    # Check intervals are valid [low, high]
    for sc_key, ci in wilson_cis.items():
        assert len(ci) == 2
        assert 0.0 <= ci[0] <= ci[1] <= 1.0


def test_existing_authentication_behavior_preserved(monkeypatch):
    """8. Existing authentication behavior remains unchanged."""
    monkeypatch.setenv(QDS_API_KEY_ENV_VAR, "sih-secret-test-key-42")

    # Access without auth -> 401
    r_unauth = client.get("/api/v1/evaluation/accuracy")
    assert r_unauth.status_code == 401

    r_unauth_det = client.post("/api/v1/detect", json={
        "measurement_data": {"measurement_counts": {"00": 256, "11": 256}, "fidelity": 0.99}
    })
    assert r_unauth_det.status_code == 401

    # Access with auth -> 200
    headers = {"Authorization": "Bearer sih-secret-test-key-42"}
    r_auth = client.get("/api/v1/evaluation/accuracy", headers=headers)
    assert r_auth.status_code == 200

    r_auth_det = client.post("/api/v1/detect", json={
        "measurement_data": {"measurement_counts": {"00": 256, "11": 256}, "fidelity": 0.99}
    }, headers=headers)
    assert r_auth_det.status_code == 200
    assert "quantum_security_bounds" in r_auth_det.json()


def test_existing_audit_behavior_preserved():
    """9. Existing audit behavior remains unchanged (detection events logged to audit ledger)."""
    initial_count = ledger.count()
    test_session = "sih-audit-test-session-101"

    r = client.post("/api/v1/detect", json={
        "measurement_data": {
            "measurement_counts": {"00": 512, "11": 512},
            "fidelity": 0.99,
            "session_id": test_session,
        }
    })
    assert r.status_code == 200
    assert ledger.count() == initial_count + 1

    # Verify latest record in ledger matches
    latest = ledger.get_records(limit=1)[0]
    assert latest.session_id == test_session
    assert latest.event_type == "THREAT_DETECTION"


def test_existing_threat_classification_behavior_preserved():
    """10. Existing threat classification behavior remains unchanged."""
    # 1. Clean data -> SECURE, NONE, is_malicious=False
    r_clean = client.post("/api/v1/detect", json={
        "measurement_data": {
            "measurement_counts": {"00": 500, "11": 500},
            "fidelity": 0.99,
            "measured_qber": 0.01,
        }
    })
    assert r_clean.status_code == 200
    d_clean = r_clean.json()
    assert d_clean["is_malicious"] is False
    assert d_clean["recommended_action"] == "NONE"
    assert d_clean["qber_classification"] == "SECURE"

    # 2. Compromised data (high QBER) -> COMPROMISED, ABORT, is_malicious=True
    r_bad = client.post("/api/v1/detect", json={
        "measurement_data": {
            "measurement_counts": {"00": 250, "01": 250, "10": 250, "11": 250},
            "fidelity": 0.50,
            "measured_qber": 0.50,
        }
    })
    assert r_bad.status_code == 200
    d_bad = r_bad.json()
    assert d_bad["is_malicious"] is True
    assert d_bad["recommended_action"] == "ABORT"
    assert d_bad["qber_classification"] == "COMPROMISED"
